### ISSUE TITLE
Using th beam-sample.lua on CPU

### ISSUE THREAD

**Issue by D063520** [pvougiou/Neural-Wikipedian#1]
Hi Pavlos, 

I was trying to execute one of your scripts on CPU only, but something seams not be set. Can you give a look. Can also be that I do not understand it well, I do not know lua:

Warning: Either cunn or cutorch was not found. Falling gracefully to CPU...	
/home/dd77474h/torch/install/bin/luajit: beam-sample.lua:26: attempt to index global 'params' (a nil value)
stack traceback:
	beam-sample.lua:26: in main chunk
	[C]: in function 'dofile'
	...474h/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

Salut
Dennis

**Comment by pvougiou** [comment]
Hi Dennis,

I suspect that the issue is that you are attempting to generate summaries using one of the pre-trained models without having NVIDIA CUDA installed. In the current setup should you wish to generate summaries using the provided models, the NVIDIA CUDA drivers along with the `cutorch` and `cunn` Lua packages should be installed in your machine. Assuming that [Torch](http://torch.ch/) and CUDA are already set up, the latter can be installed by running:
  ```sh
  luarocks install cutorch
  luarocks install cunn
  ```

Nonetheless, I updated the beam-sampling scripts (c349ab110d53c141e5428002ce3dc9fda5cef1e0) for both Triples2GRU and Triples2LSTM in order to display a more appropriate error message in case the user attempts to load a model that has been trained on the GPU without the required drivers.

Kind regards,
Pavlos
